### ISSUE TITLE
Unknown MythicMobs error

### ISSUE THREAD

**Issue by jacklollz2** [ArcanePlugins/LevelledMobs#430]
Unknown error with MythicMobs

git-Purpur-1834 (MC: 1.19.2)

```
[17:54:32 ERROR]: Could not pass event EntityDeathEvent to LevelledMobs v3.8.2 b721
java.lang.NoClassDefFoundError: io/lumine/mythic/bukkit/commands/BaseCommand
        at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:?]
        at java.lang.Class.getDeclaredField(Unknown Source) ~[?:?]
        at me.lokka30.levelledmobs.util.MythicMobUtils.getMythicMobInfo(MythicMobUtils.java:38) ~[LevelledMobs-3.8.2 b721.jar:?]
        at me.lokka30.levelledmobs.managers.LevelManager.setLevelledItemDrops(LevelManager.java:528) ~[LevelledMobs-3.8.2 b721.jar:?]
        at me.lokka30.levelledmobs.listeners.EntityDeathListener.onDeath(EntityDeathListener.java:106) ~[LevelledMobs-3.8.2 b721.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor902.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1834]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:887) ~[purpur-1.19.2.jar:git-Purpur-1834]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1805) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1700) ~[?:?]
        at net.minecraft.world.entity.raid.Raider.die(Raider.java:174) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1515) ~[?:?]
        at net.minecraft.world.entity.raid.Raider.hurt(Raider.java:299) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1363) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2198) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:3080) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:3000) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1834]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1834]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1834]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1834]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1834]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1834]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1834]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1834]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.mythic.bukkit.commands.BaseCommand
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 39 more
```

**Comment by jacklollz2** [comment]
Something I've noticed, entities from mob spawners seem to not get levels anymore.

**Comment by lokka30** [comment]
> Unknown error with MythicMobs
> 
> git-Purpur-1834 (MC: 1.19.2)
> 
> ```
> [17:54:32 ERROR]: Could not pass event EntityDeathEvent to LevelledMobs v3.8.2 b721
> java.lang.NoClassDefFoundError: io/lumine/mythic/bukkit/commands/BaseCommand
>         at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
>         at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:?]
>         at java.lang.Class.getDeclaredField(Unknown Source) ~[?:?]
>         at me.lokka30.levelledmobs.util.MythicMobUtils.getMythicMobInfo(MythicMobUtils.java:38) ~[LevelledMobs-3.8.2 b721.jar:?]
>         at me.lokka30.levelledmobs.managers.LevelManager.setLevelledItemDrops(LevelManager.java:528) ~[LevelledMobs-3.8.2 b721.jar:?]
>         at me.lokka30.levelledmobs.listeners.EntityDeathListener.onDeath(EntityDeathListener.java:106) ~[LevelledMobs-3.8.2 b721.jar:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor902.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1834]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:887) ~[purpur-1.19.2.jar:git-Purpur-1834]
>         at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1805) ~[?:?]
>         at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1700) ~[?:?]
>         at net.minecraft.world.entity.raid.Raider.die(Raider.java:174) ~[?:?]
>         at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1515) ~[?:?]
>         at net.minecraft.world.entity.raid.Raider.hurt(Raider.java:299) ~[?:?]
>         at net.minecraft.world.entity.player.Player.attack(Player.java:1363) ~[?:?]
>         at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2198) ~[?:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:3080) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:3000) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
>         at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
>         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1834]
>         at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
>         at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
>         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1834]
>         at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1834]
>         at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
>         at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1834]
>         at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1834]
>         at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
>         at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1834]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1834]
>         at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1834]
>         at java.lang.Thread.run(Unknown Source) ~[?:?]
> Caused by: java.lang.ClassNotFoundException: io.lumine.mythic.bukkit.commands.BaseCommand
>         at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
>         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
>         ... 39 more
> ```

please also send your mythic mobs version



> Something I've noticed, entities from mob spawners seem to not get levels anymore.

check [here](https://github.com/ArcanePlugins/LevelledMobs/wiki/Frequently-Asked-Questions#how-do-i-make-mobs-from-monster-spawners-levelled)

**Comment by jacklollz2** [comment]
MythicMobs v5.1.4-3aa1b5d2

**Comment by jacklollz2** [comment]
> please also send your mythic mobs version
> 
> > Something I've noticed, entities from mob spawners seem to not get levels anymore.
> 
> check [here](https://github.com/ArcanePlugins/LevelledMobs/wiki/Frequently-Asked-Questions#how-do-i-make-mobs-from-monster-spawners-levelled)

That got the mob spawners working again, thanks, but the error is still there.

**Comment by stumper66** [comment]
I can't reproduce your issue with the same MM version and LM version. Run command /ver
then show us the output.

**Comment by jacklollz2** [comment]
Current: git-Purpur-1834 (MC: 1.19.2)*
Previous: git-Purpur-1817 (MC: 1.19.2)
* You are 11 version(s) behind
Download the new version at: https://purpurmc.org/downloads

**Comment by jacklollz2** [comment]
Got some insight, apparently the MythicMobs plugin was disabled, guess I'll have to figure out why it was disabled
