### ISSUE TITLE
First start with default config and.. bum

### ISSUE THREAD

**Issue by smscentras** [ArcanePlugins/LevelledMobs#467]
[04:30:18 WARN]:        at java.base/jdk.internal.util.random.RandomSupport.checkRange(RandomSupport.java:232)
[04:30:18 WARN]:        at java.base/java.util.random.RandomGenerator.nextInt(RandomGenerator.java:679)
[04:30:18 WARN]:        at java.base/java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:458)
[04:30:18 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.rules.strategies.RandomLevellingStrategy.generateLevel(RandomLevellingStrategy.java:54)
[04:30:18 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.rules.strategies.RandomLevellingStrategy.generateLevel(RandomLevellingStrategy.java:39)
[04:30:18 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.managers.LevelManager.generateRandomLevel(LevelManager.java:245)
[04:30:18 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.managers.LevelManager.generateLevel(LevelManager.java:219)
[04:30:18 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.listeners.EntitySpawnListener.lmSpawnerSpawn(EntitySpawnListener.java:216)
[04:30:18 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.listeners.EntitySpawnListener.preprocessMob(EntitySpawnListener.java:291)
[04:30:18 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.managers.MobsQueueManager.processItem(MobsQueueManager.java:101)
[04:30:18 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.managers.MobsQueueManager.mainThread(MobsQueueManager.java:82)
[04:30:18 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.managers.MobsQueueManager.lambda$start$0(MobsQueueManager.java:44)
[04:30:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[04:30:18 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[04:30:18 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[04:30:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:30:18 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:30:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
[04:30:48 WARN]:        at java.base/jdk.internal.util.random.RandomSupport.checkRange(RandomSupport.java:232)
[04:30:48 WARN]:        at java.base/java.util.random.RandomGenerator.nextInt(RandomGenerator.java:679)
[04:30:48 WARN]:        at java.base/java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:458)
[04:30:48 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.rules.strategies.RandomLevellingStrategy.generateLevel(RandomLevellingStrategy.java:54)
[04:30:48 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.rules.strategies.RandomLevellingStrategy.generateLevel(RandomLevellingStrategy.java:39)
[04:30:48 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.managers.LevelManager.generateRandomLevel(LevelManager.java:245)
[04:30:48 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.managers.LevelManager.generateLevel(LevelManager.java:219)
[04:30:48 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.listeners.EntitySpawnListener.lmSpawnerSpawn(EntitySpawnListener.java:216)
[04:30:48 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.listeners.EntitySpawnListener.preprocessMob(EntitySpawnListener.java:291)
[04:30:48 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.managers.MobsQueueManager.processItem(MobsQueueManager.java:101)
[04:30:48 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.managers.MobsQueueManager.mainThread(MobsQueueManager.java:82)
[04:30:48 WARN]:        at LevelledMobs-3.13.1 b797.jar//me.lokka30.levelledmobs.managers.MobsQueueManager.lambda$start$0(MobsQueueManager.java:44)
[04:30:48 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[04:30:48 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[04:30:48 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[04:30:48 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[04:30:48 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[04:30:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)

**Server software**
Paper

**Server version**
Minecraft 1.20.2

**LevelledMobs version**
3.13.1 b797

**Config files, if applicable**
Default config

**Comment by stumper66** [comment]
Hello @smscentras I can't reproduce this error. I suspect you don't have a default config. Can you please upload your rules.yml ?

**Comment by smscentras** [comment]
[rules.yml.txt](https://github.com/ArcanePlugins/LevelledMobs/files/13405792/rules.yml.txt)
 All default

**Comment by smscentras** [comment]
Found when problem:
 -when placing on the ground your spawner.

**Comment by UltimaOath** [comment]
@smscentras would you please perform `/lm info` and `/version` from your server setup so I can better try to reproduce?

**Comment by smscentras** [comment]
![info](https://github.com/ArcanePlugins/LevelledMobs/assets/130366229/d95a178f-19e5-4ccb-9211-e6ebd8f935f3)

**Comment by smscentras** [comment]
I'm using SilkSPawners too: https://www.spigotmc.org/resources/silkspawners-versions-1-8-8-1-20-1.60063/

**Comment by smscentras** [comment]
I will try,
maybe there is problem with CMI? He have a lot of features...

**Comment by UltimaOath** [comment]
Sorry I hadn't had a chance to test personally super busy with work atm but
will make effort. My first suggestion is to try the same scenario with silk
spawner removed to see if that is a symptom of the issue. If it doesn't
cause the error to happen it might point to a culprit that can cause
unexpected behavior.

**Comment by smscentras** [comment]
With v3.13.2 b799 dont have errors.
Thank you
