### ISSUE TITLE
Thread Region Scheduler Thread #7 failed main thread check: Accessing entity state off owning region's thread

### ISSUE THREAD

**Issue by RitaSister** [ArcanePlugins/LevelledMobs#511]
**Describe the bug**
Thread Region Scheduler Thread #7 failed main thread check: Accessing entity state off owning region's thread

**Steps to Reproduce**
just running on Folia with mojmapping

**Expected behavior**
[Logs](https://mclo.gs/Xfp3QCr)

**Screenshots**
nothing

**Server software**
Folia

**Server version**
[12:10:11 INFO]: This server is running Folia version 1.21.1-DEV-dev/1.21.1@2e7bc07 (2024-11-15T11:11:30Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.4-DEV-d4bc338 (MC: 1.21.4)

**LevelledMobs version**
> version LevelledMobs
[12:10:23 INFO]: LevelledMobs version 4.2.0.1 b93
[12:10:23 INFO]: The Ultimate RPG Mob Levelling Solution
[12:10:23 INFO]: Website: https://github.com/ArcanePlugins/LevelledMobs/
[12:10:23 INFO]: Authors: PenalBuffalo, lokka30 and UltimaOath

**Comment by RitaSister** [comment]
I know this bug, because if plugin try get access from first thread to another thread without access and needed schedulers for this fix this problem

**Comment by RitaSister** [comment]
need using entity scheduler for checking entity's

**Comment by RitaSister** [comment]
https://mclo.gs/dcu1eM0

**Comment by RitaSister** [comment]
https://mclo.gs/2IUq0n6

**Comment by RitaSister** [comment]
[15:02:32 WARN]: [LevelledMobs] Entity task for LevelledMobs v4.2.0.2 b98 generated an exception
java.lang.NullPointerException: null                                                                                                                                                           at LevelledMobs-4.2.0.2.b98.jar/io.github.arcaneplugins.levelledmobs.wrappers.LivingEntityWrapper.getLivingEntity(LivingEntityWrapper.kt:434) ~[LevelledMobs-4.2.0.2.b98.jar:?]        at LevelledMobs-4.2.0.2.b98.jar/io.github.arcaneplugins.levelledmobs.managers.MobDataManager$Companion.populateAttributeCache(MobDataManager.kt:85) ~[LevelledMobs-4.2.0.2.b98.jar:?]
        at LevelledMobs-4.2.0.2.b98.jar/io.github.arcaneplugins.levelledmobs.managers.MobDataManager$Companion.populateAttributeCache$default(MobDataManager.kt:77) ~[LevelledMobs-4.2.0.2.b98.jar:?]
        at LevelledMobs-4.2.0.2.b98.jar/io.github.arcaneplugins.levelledmobs.listeners.EntityDamageListener.processRangedDamage$lambda$2(EntityDamageListener.kt:240) ~[LevelledMobs-4.2.0.2.b98.jar:?]
        at LevelledMobs-4.2.0.2.b98.jar/io.github.arcaneplugins.levelledmobs.wrappers.SchedulerWrapper.run$lambda$0(SchedulerWrapper.kt:52) ~[LevelledMobs-4.2.0.2.b98.jar:?]                  at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:168) ~[folia-1.21.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:115) ~[folia-1.21.4.jar:?]                                     at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:181) ~[folia-1.21.4.jar:1.21.4-DEV-290f789]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1658) ~[folia-1.21.4.jar:1.21.4-DEV-290f789]                                                                   at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.21.4.jar:1.21.4-DEV-290f789]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[folia-1.21.4.jar:1.21.4-DEV-290f789]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[concurrentutil-0.0.3.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by stumper66** [comment]
@RitaSister fixed with LevelledMobs v4.3.0 b99

**Comment by RitaSister** [comment]
> [@RitaSister](https://github.com/RitaSister) fixed with LevelledMobs v4.3.0 b99

where can download?

**Comment by stumper66** [comment]
In the discord under #dev-builds

**Comment by RitaSister** [comment]
[13:45:08 WARN]: [LevelledMobs] Async task for LevelledMobs v4.3.0 b100 generated an exception
java.util.ConcurrentModificationException: null
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095) ~[?:?]
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049) ~[?:?]
        at LevelledMobs-4.3.0 b100.jar/io.github.arcaneplugins.levelledmobs.misc.NametagTimerChecker.processCooldownQueue(NametagTimerChecker.kt:85) ~[LevelledMobs-4.3.0 b100.jar:?]
        at LevelledMobs-4.3.0 b100.jar/io.github.arcaneplugins.levelledmobs.misc.NametagTimerChecker.checkNametags(NametagTimerChecker.kt:56) ~[LevelledMobs-4.3.0 b100.jar:?]
        at LevelledMobs-4.3.0 b100.jar/io.github.arcaneplugins.levelledmobs.managers.LevelManager.startNametagTimer$lambda$38(LevelManager.kt:1138) ~[LevelledMobs-4.3.0 b100.jar:?]
        at LevelledMobs-4.3.0 b100.jar/io.github.arcaneplugins.levelledmobs.wrappers.SchedulerWrapper.runTaskTimerAsynchronously$lambda$1(SchedulerWrapper.kt:85) ~[LevelledMobs-4.3.0 b100.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.21.4.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:45:40 WARN]: [LevelledMobs] Async task for LevelledMobs v4.3.0 b100 generated an exception
java.util.ConcurrentModificationException: null
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095) ~[?:?]
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049) ~[?:?]
        at LevelledMobs-4.3.0 b100.jar/io.github.arcaneplugins.levelledmobs.misc.NametagTimerChecker.processCooldownQueue(NametagTimerChecker.kt:85) ~[LevelledMobs-4.3.0 b100.jar:?]
        at LevelledMobs-4.3.0 b100.jar/io.github.arcaneplugins.levelledmobs.misc.NametagTimerChecker.checkNametags(NametagTimerChecker.kt:56) ~[LevelledMobs-4.3.0 b100.jar:?]
        at LevelledMobs-4.3.0 b100.jar/io.github.arcaneplugins.levelledmobs.managers.LevelManager.startNametagTimer$lambda$38(LevelManager.kt:1138) ~[LevelledMobs-4.3.0 b100.jar:?]
        at LevelledMobs-4.3.0 b100.jar/io.github.arcaneplugins.levelledmobs.wrappers.SchedulerWrapper.runTaskTimerAsynchronously$lambda$1(SchedulerWrapper.kt:85) ~[LevelledMobs-4.3.0 b100.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.21.4.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

https://mclo.gs/rey6P7h

Server information:
[13:49:31 INFO]: This server is running Folia version 1.21.4-DEV-dev/hard-fork@4e7607d (1970-01-01T00:00:00Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.4-DEV-290f789 (MC: 1.21.4)

**Comment by RitaSister** [comment]
+1 more-more details about new [errors](https://mclo.gs/51HSvas#L4971)

**Comment by stumper66** [comment]
Folia is no longer supported

**Comment by RitaSister** [comment]
In future I can do fork for return support for folia. But now I can't do it, sorry
